[build]
  base = "frontend"
  publish = "build"
<<<<<<< HEAD
  command = "npm run build"
=======
  command = "bun run build"
>>>>>>> 179e0b9 (commit)

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
